local categories = {
    ["Modbridge V2"] = {
        "models/modbridge_v2/corridors/bridges/round_s.mdl",
        "models/modbridge_v2/corridors/bridges/triangle_s.mdl",
        "models/modbridge_v2/corridors/bridges/triangle_sl.mdl",
        "models/modbridge_v2/corridors/bridges/triangle_slr.mdl",
        "models/modbridge_v2/corridors/bridges/triangle_sq.mdl",
        "models/modbridge_v2/corridors/height_transfers/s1_st.mdl",
        "models/modbridge_v2/corridors/height_transfers/s1.mdl",
        "models/modbridge_v2/corridors/height_transfers/s2_st.mdl",
        "models/modbridge_v2/corridors/height_transfers/s2.mdl",
        "models/modbridge_v2/corridors/height_transfers/s3_st.mdl",
        "models/modbridge_v2/corridors/height_transfers/s3.mdl",
        "models/modbridge_v2/corridors/height_transfers/sp3_1.mdl",
        "models/modbridge_v2/corridors/height_transfers/sp3_2.mdl",
        "models/modbridge_v2/corridors/misc/pillar_double.mdl",
        "models/modbridge_v2/corridors/misc/pillar.mdl",
        "models/modbridge_v2/corridors/misc/wall.mdl",
        "models/modbridge_v2/corridors/size1/3way.mdl",
        "models/modbridge_v2/corridors/size1/4way.mdl",
        "models/modbridge_v2/corridors/size1/deadend.mdl",
        "models/modbridge_v2/corridors/size1/glass_0p1.mdl",
        "models/modbridge_v2/corridors/size1/glass_0p2.mdl",
        "models/modbridge_v2/corridors/size1/glass_0p3.mdl",
        "models/modbridge_v2/corridors/size1/glass_1p.mdl",
        "models/modbridge_v2/corridors/size1/glass_2p.mdl",
        "models/modbridge_v2/corridors/size1/glassend.mdl",
        "models/modbridge_v2/corridors/size1/straight1_sw.mdl",
        "models/modbridge_v2/corridors/size1/straight1.mdl",
        "models/modbridge_v2/corridors/size1/straight1r.mdl",
        "models/modbridge_v2/corridors/size1/straight2_sw.mdl",
        "models/modbridge_v2/corridors/size1/straight2.mdl",
        "models/modbridge_v2/corridors/size1/straight2r.mdl",
        "models/modbridge_v2/corridors/size1/straight3_sw.mdl",
        "models/modbridge_v2/corridors/size1/straight3.mdl",
        "models/modbridge_v2/corridors/size1/straight3r.mdl",
        "models/modbridge_v2/corridors/size1/turn.mdl",
        "models/modbridge_v2/corridors/size2/3way.mdl",
        "models/modbridge_v2/corridors/size2/4way.mdl",
        "models/modbridge_v2/corridors/size2/deadend.mdl",
        "models/modbridge_v2/corridors/size2/glass_0p1.mdl",
        "models/modbridge_v2/corridors/size2/glass_0p2.mdl",
        "models/modbridge_v2/corridors/size2/glass_0p3.mdl",
        "models/modbridge_v2/corridors/size2/glass_1p.mdl",
        "models/modbridge_v2/corridors/size2/glass_2p.mdl",
        "models/modbridge_v2/corridors/size2/glassend.mdl",
        "models/modbridge_v2/corridors/size2/straight1_sw.mdl",
        "models/modbridge_v2/corridors/size2/straight1.mdl",
        "models/modbridge_v2/corridors/size2/straight1r.mdl",
        "models/modbridge_v2/corridors/size2/straight2_sw.mdl",
        "models/modbridge_v2/corridors/size2/straight2.mdl",
        "models/modbridge_v2/corridors/size2/straight2r.mdl",
        "models/modbridge_v2/corridors/size2/straight3_sw.mdl",
        "models/modbridge_v2/corridors/size2/straight3.mdl",
        "models/modbridge_v2/corridors/size2/straight3r.mdl",
        "models/modbridge_v2/corridors/size2/turn.mdl",
        "models/modbridge_v2/corridors/size3/3way.mdl",
        "models/modbridge_v2/corridors/size3/4way.mdl",
        "models/modbridge_v2/corridors/size3/deadend.mdl",
        "models/modbridge_v2/corridors/size3/glass_0p1.mdl",
        "models/modbridge_v2/corridors/size3/glass_0p2.mdl",
        "models/modbridge_v2/corridors/size3/glass_0p3.mdl",
        "models/modbridge_v2/corridors/size3/glass_1p.mdl",
        "models/modbridge_v2/corridors/size3/glass_2p.mdl",
        "models/modbridge_v2/corridors/size3/glassend.mdl",
        "models/modbridge_v2/corridors/size3/straight1_sw.mdl",
        "models/modbridge_v2/corridors/size3/straight1.mdl",
        "models/modbridge_v2/corridors/size3/straight1r.mdl",
        "models/modbridge_v2/corridors/size3/straight2_sw.mdl",
        "models/modbridge_v2/corridors/size3/straight2.mdl",
        "models/modbridge_v2/corridors/size3/straight2r.mdl",
        "models/modbridge_v2/corridors/size3/straight3_sw.mdl",
        "models/modbridge_v2/corridors/size3/straight3.mdl",
        "models/modbridge_v2/corridors/size3/straight3r.mdl",
        "models/modbridge_v2/corridors/size3/turn.mdl",
        "models/modbridge_v2/corridors/size3x2/3way.mdl",
        "models/modbridge_v2/corridors/size3x2/4way.mdl",
        "models/modbridge_v2/corridors/size3x2/d32_3c.mdl",
        "models/modbridge_v2/corridors/size3x2/d32_3l.mdl",
        "models/modbridge_v2/corridors/size3x2/d32_3r.mdl",
        "models/modbridge_v2/corridors/size3x2/deadend.mdl",
        "models/modbridge_v2/corridors/size3x2/glassend.mdl",
        "models/modbridge_v2/corridors/size3x2/straight1.mdl",
        "models/modbridge_v2/corridors/size3x2/straight2.mdl",
        "models/modbridge_v2/corridors/size3x2/straight3.mdl",
        "models/modbridge_v2/corridors/size3x2/turn.mdl",
        "models/modbridge_v2/corridors/splitters/c1_32.mdl",
        "models/modbridge_v2/corridors/splitters/c2_1.mdl",
        "models/modbridge_v2/corridors/splitters/c2_3.mdl",
        "models/modbridge_v2/corridors/splitters/c2_32.mdl",
        "models/modbridge_v2/corridors/splitters/c2_3c.mdl",
        "models/modbridge_v2/corridors/splitters/c2_3l.mdl",
        "models/modbridge_v2/corridors/splitters/c2_3r.mdl",
        "models/modbridge_v2/corridors/splitters/c3_1.mdl",
        "models/modbridge_v2/corridors/splitters/c3_1c.mdl",
        "models/modbridge_v2/corridors/splitters/c3_1l.mdl",
        "models/modbridge_v2/corridors/splitters/c3_1r.mdl",
        "models/modbridge_v2/corridors/splitters/c3_32.mdl",
        "models/modbridge_v2/corridors/splitters/f1_3.mdl",
        "models/modbridge_v2/corridors/splitters/s1_2.mdl",
        "models/modbridge_v2/corridors/splitters/s1_3.mdl",
        "models/modbridge_v2/corridors/splitters/s2_3.mdl",
        "models/modbridge_v2/corridors/splitters/s3_32.mdl",
        "models/modbridge_v2/doors/hangar1_alt_frame.mdl",
        "models/modbridge_v2/doors/hangar1_door.mdl",
        "models/modbridge_v2/doors/hangar1_frame.mdl",
        "models/modbridge_v2/external_decor/round_semicircle1.mdl",
        "models/modbridge_v2/external_decor/round_semicircle2.mdl",
        "models/modbridge_v2/external_decor/round_semicircle3.mdl",
        "models/modbridge_v2/external_decor/round_semicirclec.mdl",
        "models/modbridge_v2/external_decor/round_wedge1.mdl",
        "models/modbridge_v2/external_decor/round_wedge2.mdl",
        "models/modbridge_v2/external_decor/round_wedge3.mdl",
        "models/modbridge_v2/external_decor/round_wedgec.mdl"
    },

    ["4D Corridors"] = {
        "models/4dpack/corridors/3way111.mdl",
        "models/4dpack/corridors/3way221.mdl",
        "models/4dpack/corridors/3way331.mdl",
        "models/4dpack/corridors/3way332.mdl",
        "models/4dpack/corridors/4way111.mdl",
        "models/4dpack/corridors/4way221.mdl",
        "models/4dpack/corridors/4way331.mdl",
        "models/4dpack/corridors/4way332.mdl",
        "models/4dpack/corridors/bridge221.mdl",
        "models/4dpack/corridors/bridge331.mdl",
        "models/4dpack/corridors/deadend111.mdl",
        "models/4dpack/corridors/deadend211.mdl",
        "models/4dpack/corridors/deadend311.mdl",
        "models/4dpack/corridors/deadend312.mdl",
        "models/4dpack/corridors/deadend332.mdl",
        "models/4dpack/corridors/glassend111.mdl",
        "models/4dpack/corridors/glassend211.mdl",
        "models/4dpack/corridors/glassend311.mdl",
        "models/4dpack/corridors/splitter211-21.mdl",
        "models/4dpack/corridors/splitter311-31.mdl",
        "models/4dpack/corridors/splitter311-31c.mdl",
        "models/4dpack/corridors/splitter311-31l.mdl",
        "models/4dpack/corridors/splitter311-31r.mdl",
        "models/4dpack/corridors/splitter311-32.mdl",
        "models/4dpack/corridors/splitter332-21.mdl",
        "models/4dpack/corridors/straight111.mdl",
        "models/4dpack/corridors/straight121.mdl",
        "models/4dpack/corridors/straight131.mdl",
        "models/4dpack/corridors/straight211.mdl",
        "models/4dpack/corridors/straight221.mdl",
        "models/4dpack/corridors/straight231.mdl",
        "models/4dpack/corridors/straight311.mdl",
        "models/4dpack/corridors/straight312.mdl",
        "models/4dpack/corridors/straight321.mdl",
        "models/4dpack/corridors/straight322.mdl",
        "models/4dpack/corridors/straight331.mdl",
        "models/4dpack/corridors/straight332.mdl",
        "models/4dpack/corridors/tribridge221.mdl",
        "models/4dpack/corridors/tribridge331.mdl",
        "models/4dpack/corridors/turn111.mdl",
        "models/4dpack/corridors/turn221.mdl",
        "models/4dpack/corridors/turn331.mdl",
        "models/4dpack/corridors/turn332.mdl",
        "models/4dpack/elevators/cage.mdl",
        "models/4dpack/elevators/shafth.mdl",
        "models/4dpack/elevators/shaftl.mdl",
        "models/4dpack/elevators/shaftm.mdl",
        "models/4dpack/elevators/shaftsh.mdl",
        "models/4dpack/elevators/shaftsl.mdl",
        "models/4dpack/elevators/shaftsm.mdl",
        "models/4dpack/elevators/shafttube1.mdl",
        "models/4dpack/elevators/shafttube2.mdl",
        "models/4dpack/elevators/shafttube3.mdl",
        "models/4dpack/external decor/3way332.mdl"
    },

    ["Modbridge Extras"] = {
        "models/veegi/modbridge/core/sc-121g.mdl",
        "models/veegi/modbridge/core/sc-121g2.mdl",
        "models/veegi/modbridge/core/sc-121g3.mdl",
        "models/veegi/modbridge/core/x-211.mdl",
        "models/veegi/modbridge/core/x-311.mdl",
        "models/veegi/modbridge/core/x-321.mdl",
        "models/veegi/modbridge/plate/flat/s11g2c.mdl",
        "models/veegi/modbridge/plate/flat/s11gc.mdl",
        "models/veegi/modbridge/plate/flat/s31gc.mdl",
        "models/the_one_and_only_tee/exterior/corner_111.mdl",
        "models/the_one_and_only_tee/exterior/wedge_111.mdl",
        "models/the_one_and_only_tee/exterior/wedge_131.mdl",
        "models/4dpack/external decor/corner331.mdl",
        "models/4dpack/external decor/t131.mdl",
        "models/4dpack/external decor/t231.mdl",
        "models/4dpack/external decor/t331.mdl",
        "models/4dpack/external decor/wedge331.mdl"
    },

    ["Turrets"] = {
        "models/4dpack/turrets/dual_turret_base.mdl",
        "models/4dpack/turrets/dual_turret_body.mdl",
        "models/4dpack/turrets/dual_turret_body2.mdl",
        "models/4dpack/turrets/dual_turret_cannon.mdl",
        "models/4dpack/turrets/turret_base.mdl",
        "models/4dpack/turrets/turret_body.mdl",
        "models/4dpack/turrets/turret_body2.mdl",
        "models/4dpack/turrets/turret_cannon.mdl",
        "models/thunaer/colonialrailgun/colonialrailgun_barrel.mdl",
        "models/thunaer/colonialrailgun/colonialrailgun_base.mdl",
        "models/thunaer/colonialrailgun/colonialrailgun_middle.mdl",
        "models/the17thdoctor/turret/farragut_turret_base.mdl",
        "models/the17thdoctor/turret/farragut_turret_cannons.mdl",
        "models/the17thdoctor/turret/farragut_turret_mount.mdl"
    },

    ["Misc."] = {
        "models/the17thdoctor/props/gate_sf1.mdl",
        "models/the17thdoctor/props/gate_sf2.mdl",
        "models/the17thdoctor/props/icodome.mdl",
        "models/the17thdoctor/props/icosphere.mdl",
        "models/the17thdoctor/props/shine_sprite.mdl",
        "models/veegi/beampad/beampad_2p.mdl",
        "models/veegi/beampad/beampad.mdl",
        "models/veegi/chip/chip.mdl",
        "models/veegi/emitter/emitter.mdl",
        "models/veegi/emitter/emitter2.mdl",
        "models/veegi/stargazer/core_admin.mdl",
        "models/veegi/stargazer/core_energy.mdl",
        "models/veegi/stargazer/core_ls.mdl",
        "models/veegi/stargazer/core_refinery.mdl",
        "models/veegi/stargazer/core_water.mdl",
        "models/veegi/stargazer/misc_collector_pump.mdl",
        "models/veegi/stargazer/misc_collector.mdl",
        "models/veegi/stargazer/misc_cylinder.mdl",
        "models/veegi/stargazer/misc_node.mdl",
        "models/veegi/stargazer/misc_vent.mdl"
    },

    [1] = "Modbridge V2",
    [2] = "4D Corridors",
    [3] = "Modbridge Extras",
    [4] = "Turrets",
    [5] = "Misc."
}

hook.Add("PopulatePropMenu", "Cookiepack - Add Spawnlist", function()
    local contents = {}
    for i = 1, #categories do
        local category = categories[i]
        local models = categories[category]

        contents[#contents+1] = { type = "header", text = category }

        for j = 1, #models do
            contents[#contents+1] = { type = "model", model = models[j] }
        end
    end

    spawnmenu.AddPropCategory("cookiepack", "Cookiepack", contents, "icon16/brick.png")
end)